### ISSUE TITLE
Conditions, Symptoms and Treatments entered during Sign-Up Disappear

### ISSUE THREAD

**Issue by LenPayne** [rubyforgood/Flaredown#401]
I just created my FlareDown account. I was using the FlareDown app on my Pixel 2 Android device.

I used the app on my phone to create my account. During the account creation process, it asked me what I would be tracking: what Conditions, Symptoms and Treatments.

So I spent 10-15 minutes filling them in, making sure that I searched for the right labels for me, for every category.

And then I got to the end and it told me I was ready for my first check-in.

And it asked me to fill all of that information in again.

I'm not sure if this is a bug in the account creation process, or what happened, but I'm frustrated that I spent that time to put the information in and it seems to have disappeared. Whether this is a UX issue, or just a simple bug.

If I get the chance, I'll investigate further myself.

Thank you @lmerriam for making this available.

NOTE: The app appears to be failing in general. Not just during Sign-Up. It was probably a fluke that I got this far.

NOTE 2: I was able to get Conditions, Symptoms and Treatments to save by switching between tabs/sections.

**Comment by lmerriam** [comment]
@LenPayne you're absolutely right, it's a bug. We've been trying to fix this particular issue for a year now! The main problem is that it doesn't always happen, and it's been hard to reliably reproduce.

It may be multivariate. We were able to reliably create the problem by removing a previously-added trackable (condition, symptom, etc) during signup/checkin, which broke the saving. We fixed that issue and thought the problem was solved, but still hear reports of it most weeks.

We have tried throttling bandwidth and disconnecting during the signup process, but that does not seem to produce the issue.

I would love any help reproducing the problem! If it happens consistently on your device could you document the steps, and relay any console errors you see? We will be able to easily fix the problem if we can just identify the source.

**Comment by compwron** [comment]
Power / @bklang this may be a real issue still- I haven't seen it lately tho. Maybe keep an eye out for bad error handling around deleting items during setup
